BASELINE_APPLICATIONS = [
    "Microsoft Edge",
    "Microsoft Office",
    "Microsoft Forms",
    "Azure Portal",
    "Microsoft Loop App",
    "Microsoft AppSource",
    "Bing",
    "Office Delve",
    "Microsoft Teams Web Client",
    "Microsoft Outlook",
    "Salesforce",
    "OfficeHome",
    "Outlook Mobile",
    "Microsoft Teams",
    "Microsoft Docs",
    "Microsoft Office 365 Portal",
    "Office 365 SharePoint Online",
    "Office 365 Exchange Online"
]